name: hyp3-lib
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For running
  - boto3>=1.36.0
  - gdal
  - lxml
  - netCDF4
  - numpy
  - pillow
  - requests
  - scipy
  - statsmodels
  - urllib3
  # For packaging, and testing
  - python-build
  - ruff
  - mypy
  - types-lxml
  - setuptools
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
