name: hyp3-lib
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For running
  - boto3
  - gdal
  - lxml
  - netCDF4
  - numpy
  - pillow
  - requests
  - scipy
  - statsmodels
  - urllib3
  # For packaging, and testing
  - python-build
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
