name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.11.2

  call-flake8-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.11.2
    with:
      local_package_names: hyp3lib
